CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1','1','f','******',1),
('2','2','d','******',1),
('1','3','s','******',2),
('1','4','a','******',1),
('1','5','a','******',2),
('1','6','d','******',1);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE=18 AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE AGE=18 AND NAME='RAM';

SELECT * FROM STUDENT WHERE NAME='RAM' OR NAME='SUJIT';

SELECT * FROM STUDENT WHERE NAME='RAM' AND AGE=20;

SELECT * FROM STUDENT WHERE AGE=18 AND (NAME='RAM' OR NAME='RAMESH