CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1','1','DELHI','******',1),
('2','2','GURGAON','******',1),
('1','3','ROHTAK','******',2),
('1','4','DELHI','******',1),
('1','5','ROHTAK','******',2),
('1','6','GURGAON','******',1);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE=1 AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE AGE=1 AND NAME='1';

SELECT * FROM STUDENT WHERE NAME='1' OR NAME='SUJIT';

SELECT * FROM STUDENT WHERE NAME='1' AND AGE=2;

SELECT * FROM STUDENT WHERE AGE=1 AND (NAME='1' OR NAME='2');